version: '3.8'
services:
  authorize:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - PORT=8087
      - MONGO_URI=mongodb+srv://admin:1@cluster0.swg4v.mongodb.net/authorize?retryWrites=true&w=majority
      - JWT_SECRET=roczzjyowiwaaiwozkgupfxwrybwchqs
      - JWT_SECRET_REFRESH=nbcaiuechasrsgyokkvvyhnxcvyizwkh
